.\" -*- nroff -*-
.TH STAPSH 8
.SH NAME
stapsh

.SH SYNOPSIS

.br
.B stapsh

.SH DESCRIPTION

The stapsh executable is used by the stap
.I \-\-remote
functionality, as a wrapper shell on the remote machines. 
It is not intended to be run directly by users.

.SH SEE ALSO
.nh
.nf
.IR stap (1)

.SH BUGS
Use the Bugzilla link of the project web page or our mailing list.
.nh
.BR http://sourceware.org/systemtap/ , <systemtap@sourceware.org> .
.hy
