.\" -*- nroff -*-
.TH STAPSH 8
.SH JMÉNO
stapsh

.SH POUŽITÍ

.br
.B stapsh

.SH POPIS

Program stapsh je využíván jako součást infrastruktury na vzdáleném stroji při
volání
.I stap \-\-remote .
Není určen pro přímé použití uživatelem

.SH VIZ TÉŽ
.nh
.nf
.IR stap (1)

.SH CHYBY
Použijte projektovou bugzillu, nebo mailing list.
.nh
.BR http://sourceware.org/systemtap/ ", " <systemtap@sourceware.org> .
.hy
.PP
.IR error::reporting (7stap),
.BR https://sourceware.org/systemtap/wiki/HowToReportBugs
.hy
